# Site settings
site_name: Charlie Collier Homepage
site_url: https://collier-p-charlie.github.io/

# Repository settings
repo_name: personal-github
repo_url: https://github.com/collier-p-charlie/

# Theme settings
theme:
  name: material
  language: en
  font:
    text: montserrat
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - CV: cv/docs.md
  - Packages:
      - "fsio": https://collier-p-charlie.github.io/fsio/
